name: "CI Build"

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/actions/setup-gradle@v3.0.0
      - run: "./oj check"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  test-functional:
    needs: check
    strategy:
      matrix:
        module: [app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/actions/setup-gradle@v3.0.0
      - run: "./oj :${{ matrix.module }}:checkEndToEnd"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  package:
    needs: check
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/actions/setup-gradle@v3.0.0
      - run: "./oj assemble${{ matrix.os }}"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  build:
    needs: [test-functional, package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/actions/setup-gradle@v3.0.0
      - run: "./oj build"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: Application Packages
          path: .oj/build/*/packages/*
