name: Build Plugin
on: [ push, pull_request ]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: gradle/jdk-version.txt
      - uses: gradle/actions/setup-gradle@v3
      - run: "./gradlew quickCheck"
      - run: "./gradlew test"
      - run: "./gradlew endToEndTest"
      - run: "./gradlew endToEndTestSlow"
